// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package note_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NoteV1Client is the client API for NoteV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoteV1Client interface {
	AddNoteV1(ctx context.Context, in *AddNoteV1Request, opts ...grpc.CallOption) (*AddNoteV1Response, error)
	RemoveNoteV1(ctx context.Context, in *RemoveNoteV1Request, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateNoteV1(ctx context.Context, in *UpdateNoteV1Request, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DescribeNoteV1(ctx context.Context, in *DescribeNoteV1Request, opts ...grpc.CallOption) (*DescribeNoteV1Response, error)
}

type noteV1Client struct {
	cc grpc.ClientConnInterface
}

func NewNoteV1Client(cc grpc.ClientConnInterface) NoteV1Client {
	return &noteV1Client{cc}
}

func (c *noteV1Client) AddNoteV1(ctx context.Context, in *AddNoteV1Request, opts ...grpc.CallOption) (*AddNoteV1Response, error) {
	out := new(AddNoteV1Response)
	err := c.cc.Invoke(ctx, "/api.note_v1.NoteV1/AddNoteV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteV1Client) RemoveNoteV1(ctx context.Context, in *RemoveNoteV1Request, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/api.note_v1.NoteV1/RemoveNoteV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteV1Client) UpdateNoteV1(ctx context.Context, in *UpdateNoteV1Request, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/api.note_v1.NoteV1/UpdateNoteV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteV1Client) DescribeNoteV1(ctx context.Context, in *DescribeNoteV1Request, opts ...grpc.CallOption) (*DescribeNoteV1Response, error) {
	out := new(DescribeNoteV1Response)
	err := c.cc.Invoke(ctx, "/api.note_v1.NoteV1/DescribeNoteV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteV1Server is the server API for NoteV1 service.
// All implementations must embed UnimplementedNoteV1Server
// for forward compatibility
type NoteV1Server interface {
	AddNoteV1(context.Context, *AddNoteV1Request) (*AddNoteV1Response, error)
	RemoveNoteV1(context.Context, *RemoveNoteV1Request) (*emptypb.Empty, error)
	UpdateNoteV1(context.Context, *UpdateNoteV1Request) (*emptypb.Empty, error)
	DescribeNoteV1(context.Context, *DescribeNoteV1Request) (*DescribeNoteV1Response, error)
	mustEmbedUnimplementedNoteV1Server()
}

// UnimplementedNoteV1Server must be embedded to have forward compatible implementations.
type UnimplementedNoteV1Server struct {
}

func (UnimplementedNoteV1Server) AddNoteV1(context.Context, *AddNoteV1Request) (*AddNoteV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNoteV1 not implemented")
}
func (UnimplementedNoteV1Server) RemoveNoteV1(context.Context, *RemoveNoteV1Request) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNoteV1 not implemented")
}
func (UnimplementedNoteV1Server) UpdateNoteV1(context.Context, *UpdateNoteV1Request) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNoteV1 not implemented")
}
func (UnimplementedNoteV1Server) DescribeNoteV1(context.Context, *DescribeNoteV1Request) (*DescribeNoteV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeNoteV1 not implemented")
}
func (UnimplementedNoteV1Server) mustEmbedUnimplementedNoteV1Server() {}

// UnsafeNoteV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteV1Server will
// result in compilation errors.
type UnsafeNoteV1Server interface {
	mustEmbedUnimplementedNoteV1Server()
}

func RegisterNoteV1Server(s grpc.ServiceRegistrar, srv NoteV1Server) {
	s.RegisterService(&NoteV1_ServiceDesc, srv)
}

func _NoteV1_AddNoteV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNoteV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteV1Server).AddNoteV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.note_v1.NoteV1/AddNoteV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteV1Server).AddNoteV1(ctx, req.(*AddNoteV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteV1_RemoveNoteV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNoteV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteV1Server).RemoveNoteV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.note_v1.NoteV1/RemoveNoteV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteV1Server).RemoveNoteV1(ctx, req.(*RemoveNoteV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteV1_UpdateNoteV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNoteV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteV1Server).UpdateNoteV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.note_v1.NoteV1/UpdateNoteV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteV1Server).UpdateNoteV1(ctx, req.(*UpdateNoteV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteV1_DescribeNoteV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeNoteV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteV1Server).DescribeNoteV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.note_v1.NoteV1/DescribeNoteV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteV1Server).DescribeNoteV1(ctx, req.(*DescribeNoteV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// NoteV1_ServiceDesc is the grpc.ServiceDesc for NoteV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.note_v1.NoteV1",
	HandlerType: (*NoteV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNoteV1",
			Handler:    _NoteV1_AddNoteV1_Handler,
		},
		{
			MethodName: "RemoveNoteV1",
			Handler:    _NoteV1_RemoveNoteV1_Handler,
		},
		{
			MethodName: "UpdateNoteV1",
			Handler:    _NoteV1_UpdateNoteV1_Handler,
		},
		{
			MethodName: "DescribeNoteV1",
			Handler:    _NoteV1_DescribeNoteV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
