// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: service.proto

package note_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddNoteV1Request with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddNoteV1Request) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddNoteV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddNoteV1RequestMultiError, or nil if none found.
func (m *AddNoteV1Request) ValidateAll() error {
	return m.validate(true)
}

func (m *AddNoteV1Request) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for ClassroomId

	// no validation rules for DocumentId

	if len(errors) > 0 {
		return AddNoteV1RequestMultiError(errors)
	}
	return nil
}

// AddNoteV1RequestMultiError is an error wrapping multiple validation errors
// returned by AddNoteV1Request.ValidateAll() if the designated constraints
// aren't met.
type AddNoteV1RequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddNoteV1RequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddNoteV1RequestMultiError) AllErrors() []error { return m }

// AddNoteV1RequestValidationError is the validation error returned by
// AddNoteV1Request.Validate if the designated constraints aren't met.
type AddNoteV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddNoteV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddNoteV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddNoteV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddNoteV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddNoteV1RequestValidationError) ErrorName() string { return "AddNoteV1RequestValidationError" }

// Error satisfies the builtin error interface
func (e AddNoteV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddNoteV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddNoteV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddNoteV1RequestValidationError{}

// Validate checks the field values on AddNoteV1Response with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddNoteV1Response) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddNoteV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddNoteV1ResponseMultiError, or nil if none found.
func (m *AddNoteV1Response) ValidateAll() error {
	return m.validate(true)
}

func (m *AddNoteV1Response) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for NoteId

	if len(errors) > 0 {
		return AddNoteV1ResponseMultiError(errors)
	}
	return nil
}

// AddNoteV1ResponseMultiError is an error wrapping multiple validation errors
// returned by AddNoteV1Response.ValidateAll() if the designated constraints
// aren't met.
type AddNoteV1ResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddNoteV1ResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddNoteV1ResponseMultiError) AllErrors() []error { return m }

// AddNoteV1ResponseValidationError is the validation error returned by
// AddNoteV1Response.Validate if the designated constraints aren't met.
type AddNoteV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddNoteV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddNoteV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddNoteV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddNoteV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddNoteV1ResponseValidationError) ErrorName() string {
	return "AddNoteV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AddNoteV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddNoteV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddNoteV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddNoteV1ResponseValidationError{}

// Validate checks the field values on RemoveNoteV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RemoveNoteV1Request) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveNoteV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RemoveNoteV1RequestMultiError, or nil if none found.
func (m *RemoveNoteV1Request) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveNoteV1Request) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return RemoveNoteV1RequestMultiError(errors)
	}
	return nil
}

// RemoveNoteV1RequestMultiError is an error wrapping multiple validation
// errors returned by RemoveNoteV1Request.ValidateAll() if the designated
// constraints aren't met.
type RemoveNoteV1RequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveNoteV1RequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveNoteV1RequestMultiError) AllErrors() []error { return m }

// RemoveNoteV1RequestValidationError is the validation error returned by
// RemoveNoteV1Request.Validate if the designated constraints aren't met.
type RemoveNoteV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveNoteV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveNoteV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveNoteV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveNoteV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveNoteV1RequestValidationError) ErrorName() string {
	return "RemoveNoteV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveNoteV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveNoteV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveNoteV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveNoteV1RequestValidationError{}

// Validate checks the field values on UpdateNoteV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateNoteV1Request) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateNoteV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateNoteV1RequestMultiError, or nil if none found.
func (m *UpdateNoteV1Request) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateNoteV1Request) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for ClassroomId

	// no validation rules for DocumentId

	if len(errors) > 0 {
		return UpdateNoteV1RequestMultiError(errors)
	}
	return nil
}

// UpdateNoteV1RequestMultiError is an error wrapping multiple validation
// errors returned by UpdateNoteV1Request.ValidateAll() if the designated
// constraints aren't met.
type UpdateNoteV1RequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateNoteV1RequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateNoteV1RequestMultiError) AllErrors() []error { return m }

// UpdateNoteV1RequestValidationError is the validation error returned by
// UpdateNoteV1Request.Validate if the designated constraints aren't met.
type UpdateNoteV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateNoteV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateNoteV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateNoteV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateNoteV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateNoteV1RequestValidationError) ErrorName() string {
	return "UpdateNoteV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateNoteV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateNoteV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateNoteV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateNoteV1RequestValidationError{}

// Validate checks the field values on DescribeNoteV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DescribeNoteV1Request) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DescribeNoteV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DescribeNoteV1RequestMultiError, or nil if none found.
func (m *DescribeNoteV1Request) ValidateAll() error {
	return m.validate(true)
}

func (m *DescribeNoteV1Request) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DescribeNoteV1RequestMultiError(errors)
	}
	return nil
}

// DescribeNoteV1RequestMultiError is an error wrapping multiple validation
// errors returned by DescribeNoteV1Request.ValidateAll() if the designated
// constraints aren't met.
type DescribeNoteV1RequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DescribeNoteV1RequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DescribeNoteV1RequestMultiError) AllErrors() []error { return m }

// DescribeNoteV1RequestValidationError is the validation error returned by
// DescribeNoteV1Request.Validate if the designated constraints aren't met.
type DescribeNoteV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeNoteV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeNoteV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeNoteV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeNoteV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeNoteV1RequestValidationError) ErrorName() string {
	return "DescribeNoteV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeNoteV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeNoteV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeNoteV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeNoteV1RequestValidationError{}

// Validate checks the field values on DescribeNoteV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DescribeNoteV1Response) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DescribeNoteV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DescribeNoteV1ResponseMultiError, or nil if none found.
func (m *DescribeNoteV1Response) ValidateAll() error {
	return m.validate(true)
}

func (m *DescribeNoteV1Response) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for ClassroomId

	// no validation rules for DocumentId

	if len(errors) > 0 {
		return DescribeNoteV1ResponseMultiError(errors)
	}
	return nil
}

// DescribeNoteV1ResponseMultiError is an error wrapping multiple validation
// errors returned by DescribeNoteV1Response.ValidateAll() if the designated
// constraints aren't met.
type DescribeNoteV1ResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DescribeNoteV1ResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DescribeNoteV1ResponseMultiError) AllErrors() []error { return m }

// DescribeNoteV1ResponseValidationError is the validation error returned by
// DescribeNoteV1Response.Validate if the designated constraints aren't met.
type DescribeNoteV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeNoteV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeNoteV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeNoteV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeNoteV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeNoteV1ResponseValidationError) ErrorName() string {
	return "DescribeNoteV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeNoteV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeNoteV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeNoteV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeNoteV1ResponseValidationError{}
